#!/bin/bash

cat /opt/kafka/config/connect-distributed.properties.template | sed \
  -e "s|{{KAFKACONNECT_BOOTSTRAP_SERVERS}}|${KAFKACONNECT_BOOTSTRAP_SERVERS:-localhost:9092}|g" \
  -e "s|{{KAFKACONNECT_GROUP_ID}}|${KAFKACONNECT_GROUP_ID:-connect-cluster}|g" \
  -e "s|{{KAFKACONNECT_KEY_CONVERTER}}|${KAFKACONNECT_KEY_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}|g" \
  -e "s|{{KAFKACONNECT_VALUE_CONVERTER}}|${KAFKACONNECT_VALUE_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}|g" \
  -e "s|{{KAFKACONNECT_KEY_CONVERTER_SCHEMAS_ENABLE}}|${KAFKACONNECT_KEY_CONVERTER_SCHEMAS_ENABLE:-true}|g" \
  -e "s|{{KAFKACONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE}}|${KAFKACONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE:-true}|g" \
  -e "s|{{KAFKACONNECT_INTERNAL_KEY_CONVERTER}}|${KAFKACONNECT_INTERNAL_KEY_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}|g" \
  -e "s|{{KAFKACONNECT_INTERNAL_VALUE_CONVERTER}}|${KAFKACONNECT_INTERNAL_VALUE_CONVERTER:-org.apache.kafka.connect.json.JsonConverter}|g" \
  -e "s|{{KAFKACONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE}}|${KAFKACONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE:-false}|g" \
  -e "s|{{KAFKACONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE}}|${KAFKACONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE:-false}|g" \
  -e "s|{{KAFKACONNECT_OFFSET_STORAGE_TOPIC}}|${KAFKACONNECT_OFFSET_STORAGE_TOPIC:-connect-offsets}|g" \
  -e "s|{{KAFKACONNECT_OFFSET_STORAGE_REPLICATION_FACTOR}}|${KAFKACONNECT_OFFSET_STORAGE_REPLICATION_FACTOR:-1}|g" \
  -e "s|{{KAFKACONNECT_CONFIG_STORAGE_TOPIC}}|${KAFKACONNECT_CONFIG_STORAGE_TOPIC:-connect-configs}|g" \
  -e "s|{{KAFKACONNECT_CONFIG_STORAGE_REPLICATION_FACTOR}}|${KAFKACONNECT_CONFIG_STORAGE_REPLICATION_FACTOR:-1}|g" \
  -e "s|{{KAFKACONNECT_STATUS_STORAGE_TOPIC}}|${KAFKACONNECT_STATUS_STORAGE_TOPIC:-connect-status}|g" \
  -e "s|{{KAFKACONNECT_STATUS_STORAGE_REPLICATION_FACTOR}}|${KAFKACONNECT_STATUS_STORAGE_REPLICATION_FACTOR:-1}|g" \
  -e "s|{{KAFKACONNECT_OFFSET_FLUSH_INTERVAL_MS}}|${KAFKACONNECT_OFFSET_FLUSH_INTERVAL_MS:-10000}|g" \
  -e "s|{{KAFKACONNECT_REST_HOST_NAME}}|${KAFKACONNECT_REST_HOST_NAME:-localhost}|g" \
  -e "s|{{KAFKACONNECT_REST_PORT}}|${KAFKACONNECT_REST_PORT:-8083}|g" \
   > /opt/kafka/config/connect-distributed.properties

cat /opt/kafka/config/connect-log4j.properties.template | sed \
  -e "s|{{KAFKACONNECT_LOG4J_ROOTLOGGER}}|${KAFKACONNECT_LOG4J_ROOTLOGGER:-INFO, stdout, connectAppender}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_STDOUT}}|${KAFKACONNECT_LOG4J_APPENDER_STDOUT:-org.apache.log4j.ConsoleAppender}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_STDOUT_LAYOUT}}|${KAFKACONNECT_LOG4J_APPENDER_STDOUT_LAYOUT:-org.apache.log4j.PatternLayout}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSATIONPATTERN}}|${KAFKACONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSATIONPATTERN:-[%d] %p %m (%c:%L)%n}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_LOGGER_ORG_APACHE_ZOOKEEPER}}|${KAFKACONNECT_LOG4J_LOGGER_ORG_APACHE_ZOOKEEPER:-ERROR}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_LOGGER_ORG_I0ITEC_ZKCLIENT}}|${KAFKACONNECT_LOG4J_LOGGER_ORG_I0ITEC_ZKCLIENT:-ERROR}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_LOGGER_ORG_REFLECTIONS}}|${KAFKACONNECT_LOG4J_LOGGER_ORG_REFLECTIONS:-ERROR}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER}}|${KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER:-org.apache.log4j.DailyRollingFileAppender}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_DATEPATTERN}}|${KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_DATEPATTERN:-'.'yyyy-MM-dd-HH}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_FILE}}|${KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_FILE:-$\{kafka.logs.dir\}/connect.log}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_LAYOUT}}|${KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_LAYOUT:-org.apache.log4j.PatternLayout}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_LAYOUT_CONVERSIONPATTERN}}|${KAFKACONNECT_LOG4J_APPENDER_CONNECTAPPENDER_LAYOUT_CONVERSIONPATTERN:-[%d] %p %m (%c:%L)%n}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER}}|${KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER:-org.apache.log4j.DailyRollingFileAppender}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_DATEPATTERN}}|${KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_DATEPATTERN:-'.'yyyy-MM-dd-HH}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_FILE}}|${KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_FILE:-\${kafka.logs.dir\}/connect-rest.log}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_LAYOUT}}|${KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_LAYOUT:-org.apache.log4j.PatternLayout}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_LAYOUT_CONVERSATIONPATTERN}}|${KAFKACONNECT_LOG4J_APPENDER_KAFKACONNECTRESTAPPENDER_LAYOUT_CONVERSATIONPATTERN:-[%d] %p %m (%c)%n}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_LOGGER_ORG_APACHE_KAFKA_CONNECT_RUNTIME_REST}}|${KAFKACONNECT_LOG4J_LOGGER_ORG_APACHE_KAFKA_CONNECT_RUNTIME_REST:-INFO, kafkaConnectRestAppender}|g" \
  -e "s|{{KAFKACONNECT_LOG4J_ADDITIVITY_ORG_APACHE_KAFKA_CONNECT_RUNTIME_REST}}|${KAFKACONNECT_LOG4J_ADDITIVITY_ORG_APACHE_KAFKA_CONNECT_RUNTIME_REST:-false}|g" \
   > /opt/kafka/config/connect-log4j.properties

echo "Starting kafka"
exec ./bin/connect-distributed.sh ./config/connect-distributed.properties
